#
# The worlds that we want to have access to bot functionality
#
FreebuildWorldNames: [W_SurvivalFreebuild]

#
# The fly speed for boters that can fly
#
FlySpeed: 0.3

#
# The mandatory cooldown time between calling /bot on and /bot off
#
CoolDownTime: 30m

eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1

commands:
  #
  # This command is dispatched when a player starts to fly in bot mode.
  # Parameters: <FlySpeed> (%.2f), <player name> (%s)
  #
  SetSpeed: speed fly %.2f %s
  
  #
  # This command is dispatched when a player tries to fly when not supposed to.
  # Parameters: -
  #
  StopFly: fly

messages:

  #
  # This message is displayed when someone tries to use bot outside the allowed worlds (see FreebuildWorldNames)
  # It has no parameters.
  #
  MustBeInFreebuildWord: You can only switch between survival and bot in the SurvivalFreebuild world.

  #
  # This message is displayed when someone switches to fast between on and off
  # Parameters: <minutes left> (%d), <seconds left> (%d)
  #
  WaitForCoolDown: The remaining cool down period for switching Freebuild mode is %d minutes and %d seconds.

  #
  # The player tried to activate bot mode, but it already was active.
  # Parameters: NONE
  #
  AlreadyOn_0: Freebuild mode is already active.

  #
  # The player tried to deactivate bot mode, but it already was deactivated.
  # Parameters: NONE
  #
  AlreadyOff_0: Survival mode is already active (bot is OFF).

  #
  # The bot mode has been successfully activated
  # Parameters: NONE
  #
  Activated_0: Freebuild mode is now active.

  #
  # The bot mode has been successfully deactivated
  # Parameters: NONE
  #
  Deactivated_0: Survival mode is now active (bot is OFF).

  #
  # Tried to release a player not in cool down.
  # Parameters: <player name>(%s)
  #
  NotInCoolDown_1: The player %s was not in cool down.

  #
  # A player has been released from cool down.
  # Parameters: <player name>(%s)
  #
  ReleasedFromCoolDown_1: The player %s was released from cool down.
