name: EithonBot
main: net.eithon.plugin.bot.Plugin
version: 0.1
author: vanbrayne
description: A Minecraft plugin for a virtual player
depend: [EithonLibrary]
commands:
  bot:
    description: Variations of survival/creative modes
    usage: /bot create
    permission-message: You don't have <permission>
permissions:
  bot.*:
    description: Gives access to all bot commands
    default: op
    bot.create: true
  bot.create:
    description: Access to /bot create command
    default: op
